import type { ComponentType } from 'react';
import type { AlertDialogProps } from './alert-dialog-props.js';
import type { AlertProps } from './alert-props.js';
import type { ApplicationProps } from './application-props.js';
import type { ArticleProps } from './article-props.js';
import type { BannerProps } from './banner-props.js';
import type { BlockQuoteProps } from './block-quote-props.js';
import type { CodeProps } from './code-props.js';
import type { ComboboxProps } from './combobox-props.js';
import type { ComplementaryProps } from './complementary-props.js';
import type { ContentInfoProps } from './content-info-props.js';
import type { DefinitionProps } from './definition-props.js';
import type { DialogProps } from './dialog-props.js';
import type { EmphasisProps } from './emphasis-props.js';
import type { FeedProps } from './feed-props.js';
import type { FigureProps } from './figure-props.js';
import type { GridProps } from './grid-props.js';
import type { HeadingProps } from './heading-props.js';
import type { ImageProps } from './image-props.js';
import type { ListProps } from './list-props.js';
import type { LogProps } from './log-props.js';
import type { MainProps } from './main-props.js';
import type { MarkProps } from './mark-props.js';
import type { MarqueeProps } from './marquee-props.js';
import type { MathProps } from './math-props.js';
import type { MenuBarProps } from './menu-bar-props.js';
import type { NavigationProps } from './navigation-props.js';
import type { NoteProps } from './note-props.js';
import type { ParagraphProps } from './paragraph-props.js';
import type { RadioGroupProps } from './radio-group-props.js';
import type { RegionProps } from './region-props.js';
import type { ScrollbarProps } from './scrollbar-props.js';
import type { SearchBoxProps } from './search-box-props.js';
import type { SearchProps } from './search-props.js';
import type { SectionFooterProps } from './section-footer-props.js';
import type { SectionHeaderProps } from './section-header-props.js';
import type { SeparatorWidgetProps } from './separator-widget-props.js';
import type { SliderProps } from './slider-props.js';
import type { SpinButtonProps } from './spin-button-props.js';
import type { StatusProps } from './status-props.js';
import type { StrongProps } from './strong-props.js';
import type { SubscriptProps } from './subscript-props.js';
import type { SuggestionProps } from './suggestion-props.js';
import type { SuperscriptProps } from './superscript-props.js';
import type { TableProps } from './table-props.js';
import type { TabsProps } from './tabs-props.js';
import type { TermProps } from './term-props.js';
import type { TextBoxProps } from './text-box-props.js';
import type { TimeProps } from './time-props.js';
import type { TimerProps } from './timer-props.js';
import type { ToolbarProps } from './toolbar-props.js';
import type { TreeGridProps } from './tree-grid-props.js';
import type { ToggleButtonProps } from './toggle-button-props.js';
import type { SwitchProps } from './switch-props.js';
import type { TooltipProps } from './tooltip-props.js';
import type { SeparatorProps } from './separator-props.js';
import type { ProgressBarProps } from './progress-bar-props.js';
import type { MeterProps } from './meter-props.js';
import type { MenuProps } from './menu-props.js';
import type { ListBoxProps } from './list-box-props.js';
import type { LinkProps } from './link-props.js';
import type { FormProps } from './form-props.js';
import type { DocumentProps } from './document-props.js';
import type { CommentProps } from './comment-props.js';
import type { CheckboxProps } from './checkbox-props.js';
import type { ButtonProps } from './button-props.js';

export default interface DesignSystem {
  readonly Alert: ComponentType<AlertProps>;
  readonly AlertDialog: ComponentType<AlertDialogProps>;
  readonly Application: ComponentType<ApplicationProps>;
  readonly Article: ComponentType<ArticleProps>;
  readonly Banner: ComponentType<BannerProps>;
  readonly BlockQuote: ComponentType<BlockQuoteProps>;
  readonly Button: ComponentType<ButtonProps>;
  readonly Checkbox: ComponentType<CheckboxProps>;
  readonly Code: ComponentType<CodeProps>;
  readonly Combobox: ComponentType<ComboboxProps>;
  readonly Comment: ComponentType<CommentProps>;
  readonly Complementary: ComponentType<ComplementaryProps>;
  readonly ContentInfo: ComponentType<ContentInfoProps>;
  readonly Definition: ComponentType<DefinitionProps>;
  readonly Dialog: ComponentType<DialogProps>;
  readonly Document: ComponentType<DocumentProps>;
  readonly Emphasis: ComponentType<EmphasisProps>;
  readonly Feed: ComponentType<FeedProps>;
  readonly Figure: ComponentType<FigureProps>;
  readonly Form: ComponentType<FormProps>;
  readonly Grid: ComponentType<GridProps>;
  readonly Heading: ComponentType<HeadingProps>;
  readonly Image: ComponentType<ImageProps>;
  readonly Link: ComponentType<LinkProps>;
  readonly List: ComponentType<ListProps>;
  readonly ListBox: ComponentType<ListBoxProps>;
  readonly Log: ComponentType<LogProps>;
  readonly Main: ComponentType<MainProps>;
  readonly Mark: ComponentType<MarkProps>;
  readonly Marquee: ComponentType<MarqueeProps>;
  readonly Math: ComponentType<MathProps>;
  readonly Menu: ComponentType<MenuProps>;
  readonly MenuBar: ComponentType<MenuBarProps>;
  readonly Meter: ComponentType<MeterProps>;
  readonly Navigation: ComponentType<NavigationProps>;
  readonly Note: ComponentType<NoteProps>;
  readonly Paragraph: ComponentType<ParagraphProps>;
  readonly ProgressBar: ComponentType<ProgressBarProps>;
  readonly RadioGroup: ComponentType<RadioGroupProps>;
  readonly Region: ComponentType<RegionProps>;
  readonly Scrollbar: ComponentType<ScrollbarProps>;
  readonly Search: ComponentType<SearchProps>;
  readonly SearchBox: ComponentType<SearchBoxProps>;
  readonly SectionFooter: ComponentType<SectionFooterProps>;
  readonly SectionHeader: ComponentType<SectionHeaderProps>;
  readonly Separator: ComponentType<SeparatorProps>;
  readonly SeparatorWidget: ComponentType<SeparatorWidgetProps>;
  readonly Slider: ComponentType<SliderProps>;
  readonly SpinButton: ComponentType<SpinButtonProps>;
  readonly Status: ComponentType<StatusProps>;
  readonly Strong: ComponentType<StrongProps>;
  readonly Subscript: ComponentType<SubscriptProps>;
  readonly Suggestion: ComponentType<SuggestionProps>;
  readonly Superscript: ComponentType<SuperscriptProps>;
  readonly Switch: ComponentType<SwitchProps>;
  readonly Table: ComponentType<TableProps>;
  readonly Tabs: ComponentType<TabsProps>;
  readonly Term: ComponentType<TermProps>;
  readonly TextBox: ComponentType<TextBoxProps>;
  readonly Time: ComponentType<TimeProps>;
  readonly Timer: ComponentType<TimerProps>;
  readonly ToggleButton: ComponentType<ToggleButtonProps>;
  readonly Toolbar: ComponentType<ToolbarProps>;
  readonly Tooltip: ComponentType<TooltipProps>;
  readonly TreeGrid: ComponentType<TreeGridProps>;
}
