CREATE TABLE IF NOT EXISTS [users] (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "firstName" VARCHAR(255) DEFAULT NULL,
  "fullName" VARCHAR(255) DEFAULT NULL,
  "gender" UNSIGNED TINYINT NOT NULL DEFAULT 0,
  "registrationTimestamp" UNSIGNED INTEGER NOT NULL
);
