CREATE TABLE IF NOT EXISTS [users] (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "firstName" TEXT DEFAULT NULL,
  "fullName" TEXT DEFAULT NULL,
  "gender" UNSIGNED INTEGER NOT NULL DEFAULT 0,
  "registrationTimestamp" UNSIGNED INTEGER NOT NULL
);
