CREATE TABLE [users] (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "firstName" VARCHAR(255) NOT NULL,
  "fullName" VARCHAR(255) NOT NULL,
  "gender" UNSIGNED TINYINT NOT NULL DEFAULT 0,
  "registrationTimestamp" UNSIGNED INTEGER NOT NULL
);
