paths:
  .github/workflows/**/*.yml:
    ignore:
      - 'missing input "app-id" which is required by action "actions/create-github-app-token@v3"'
      - 'input "client-id" is not defined in action "actions/create-github-app-token@v3"'
