# yaml-language-server: $schema=../../../schemas/github-action.jsonc
name: Setup
description: Sets up Node and installs dependencies

inputs:
  continue-on-error:
    default: 'false'
    description: Continue the workflow even if the build fails?
    required: false
  download-build:
    default: 'true'
    description: Whether to download the build artifact
    required: false
  install-browsers:
    default: 'false'
    description: Whether to install browsers
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        check-latest: true
        # Playwright fails to install on Node >=24.15.0.
        # https://github.com/microsoft/playwright/pull/40747
        node-version-file: .nvmrc
        node-version: >-
          ${{ inputs.install-browsers != 'false' && '24.15.0' || '' }}

    - name: Download build
      if: ${{ inputs.download-build == 'true' }}
      uses: actions/download-artifact@v7
      with:
        name: build

    - name: Install Debian dependencies
      continue-on-error: ${{ inputs.continue-on-error == 'true' }}
      shell: bash
      run: >-
        sudo apt-get update;
        sudo apt-get install --yes
        build-essential
        libcairo2-dev
        libgif-dev
        libjpeg-dev
        libpango1.0-dev
        librsvg2-dev;

    - name: Install NPM dependencies
      continue-on-error: ${{ inputs.continue-on-error == 'true' }}
      run: npm install --include dev
      shell: bash

    - name: Get Playwright version
      id: playwright-version
      if: inputs.install-browsers != 'false'
      run: echo "value=$(npx playwright --version)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache browsers
      id: cache-playwright
      if: inputs.install-browsers != 'false'
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: >-
          playwright-
          ${{ runner.os }}-
          ${{ steps.playwright-version.outputs.value }}

    - name: Install browsers
      continue-on-error: ${{ inputs.continue-on-error == 'true' }}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      if: >-
        inputs.install-browsers != 'false' &&
        steps.cache-playwright.outputs.cache-hit != 'true'
      run: >-
        npx playwright install --only-shell
        chromium-headless-shell firefox webkit;

    - name: Install browser dependencies
      if: inputs.install-browsers != 'false'
      run: npx playwright install-deps
      shell: bash
