# yaml-language-server: $schema=../../../schemas/github-action.jsonc
name: Setup
description: Sets up Node and installs dependencies

inputs:
  download-build:
    default: 'true'
    description: Whether to download the build artifact
    required: false
  install-browsers:
    default: 'false'
    description: Whether to install browsers
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        check-latest: true
        # Playwright fails to install on Node 26.
        # https://github.com/microsoft/playwright/pull/40747
        node-version: ${{ inputs.install-browsers != 'false' && 'lts/*' || '' }}
        node-version-file: .nvmrc
    - name: Download build
      if: ${{ inputs.download-build == 'true' }}
      uses: actions/download-artifact@v7
      with:
        name: build
    - name: Install dependencies
      shell: bash
      run: npm install
    - name: Install browsers
      if: ${{ inputs.install-browsers != 'false' }}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        npx playwright install --only-shell --with-deps \
          chromium-headless-shell firefox webkit;
