# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: Setup
description: Sets up Node and installs dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        check-latest: true
        node-version-file: .nvmrc
    - name: Install dependencies
      # Build `quisi` then reinstall so that it's a symlinked Node module.
      run: >
        npm ci;
        npm run-script build --workspace=packages/quisi;
        npm ci;
      shell: bash
