# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: Setup
description: Sets up Node and installs dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      env:
        INPUT_CACHE: npm
        INPUT_CACHE_DEPENDENCY_PATH: package-lock.json
        INPUT_CACHE-DEPENDENCY-PATH: package-lock.json
        INPUT_CHECK_LATEST: true
        INPUT_CHECK-LATEST: true
        INPUT_NODE_VERSION_FILE: .nvmrc
        INPUT_NODE-VERSION-FILE: .nvmrc
    - name: Install dependencies
      run: npm ci
      shell: bash
