enum NavigationText {
  AceAlters = 'acealters',
  Applications = 'applications',
  CloudflareWorkersAI = 'cloudflare-workers-ai',
  ConnectWithMe = 'connect-with-me',
  Bluesky = 'bluesky',
  Dashboard = 'dashboard',
  Dota2Huds = 'dota2huds',
  GitHub = 'github',
  Home = 'home',
  LinkedIn = 'linkedin',
  Medium = 'medium',
  MTGPlanechase = 'mtg-planechase',
  Packages = 'packages',
  Portfolio = 'portfolio',
  Publications = 'publications',
  Quisido = 'quisido',
  Quotes = 'quotes',
  RPGOverworldEngine = 'rpg-overworld-engine',
  Settings = 'settings',
  Tetris3DS = '3ds-tetris',
  Threads = 'threads',
  Twitter = 'twitter',
}

export default NavigationText;
