checksumBehavior: update

logFilters:
  - code: YN0060
    level: discard

packageExtensions:
  "@cypress/code-coverage@*":
    dependencies:
      "@babel/preset-env": ">=7.0.0"
      babel-loader: ">=7.0.0"
      webpack: ">=4"
  "@opentelemetry/context-zone@*":
    peerDependencies:
      "@opentelemetry/api": ^1.0.0
  "@sentry/fullstory@*":
    peerDependencies:
      "@sentry/types": ">=7.0.0"
  "@sentry/nextjs@*":
    peerDependencies:
      "@opentelemetry/api": ^1.0.0
  cypress@*:
    peerDependencies:
      bluebird: ^3.7.0
      cachedir: ^2.3.0
      minimist: ^1.2.0
      semver: ^7.5.0
  eslint-config-next@*:
    peerDependencies:
      next: "*"
  next@*:
    dependencies:
      critters: "*"
  posthog-js@^1.0.0:
    peerDependencies:
      react: "*"
    peerDependenciesMeta:
      react:
        optional: true
  vitest@*:
    dependencies:
      "@types/chai": ^5.0.0
      "@types/debug": ^4.1.12

yarnPath: .yarn/releases/yarn-4.7.0.cjs
