logFilters:
  - code: YN0060
    level: discard

packageExtensions:
  '@cypress/code-coverage@*':
    peerDependencies:
      '@babel/core': ^7.0.1
      '@babel/preset-env': ^7.0.0
      babel-loader: ^8.0.2
      webpack: ^4 || ^5
  eslint-config-react-app@*:
    peerDependencies:
      '@babel/plugin-syntax-flow': ^7.14.5
      '@babel/plugin-transform-react-jsx': ^7.16.0

yarnPath: .yarn/releases/yarn-3.2.3.cjs
