yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  # Workaround for `@react95/core` and its dependencies missing dependencies in
  #   their respective `package.json` files.
  '@react95/core@^5.7.3':
    dependencies:
      '@xstyled/system': ^1.17.1
      'styled-components': ^5.1.0
  '@xstyled/core@^1.17.1':
    dependencies:
      '@xstyled/util': ^1.17.1
  styled-components@^5.3.3:
    dependencies:
      react-is: ^17.0.2

  # Workaround for `babel-preset-react-app` missing a dependency in its
  #   `package.json` file.
  # https://github.com/facebook/create-react-app/issues/11793
  babel-preset-react-app@*:
    dependencies:
      '@babel/plugin-proposal-private-property-in-object': '*'
