const FULL_HD_HEIGHT = 1080;
const FULL_HD_WIDTH = 1920;
const FULLSCREEN_HEIGHT = 1024;
const FULLSCREEN_WIDTH = 768;
const UHD_HEIGHT = 2160;
const UHD_WIDTH = 3840;
const UHD2_HEIGHT = 4320;
const UHD2_WIDTH = 7680;
const WIDESCREEN_HD_HEIGHT = 720;
const WIDESCREEN_HD_WIDTH = 1280;

const VIEWPORTS: readonly [number, number][] = [
  // [375, 667],
  [FULLSCREEN_WIDTH, FULLSCREEN_HEIGHT],
  [WIDESCREEN_HD_WIDTH, WIDESCREEN_HD_HEIGHT],
  [FULL_HD_WIDTH, FULL_HD_HEIGHT],
  [UHD_WIDTH, UHD_HEIGHT],
  [UHD2_WIDTH, UHD2_HEIGHT],
];

export default VIEWPORTS;
