export enum MetricName {
  Favicon = 'pathname.favicon.ico',
  InvalidDatabase = 'database.invalid',
  InvalidDatabaseKeysRow = 'database.keys.row.invalid',
  InvalidDatabaseProjectsRow = 'database.projects.row.invalid',
  InvalidGetKey = 'key.get.invalid',
  InvalidOptionsProjectId = 'options.project-id.invalid',
  InvalidOrigin = 'origin.invalid',
  InvalidPathname = 'pathname.invalid',
  InvalidPermission = 'permission.invalid',
  InvalidPostKey = 'post.key.invalid',
  InvalidPrivateDataset = 'dataset.private.invalid',
  InvalidPublicDataset = 'dataset.public.invalid',
  InvalidTraceParent = 'traceparent.invalid',
  InvalidUsageDataset = 'dataset.usage.invalid',
  InvalidWorkerMetric = 'quisido.worker.metric.invalid',
  MethodNotAllowed = 'http.4xx.method.not-allowed',
  MissingGetKey = 'key.get.missing',
  MissingOrigin = 'origin.missing',
  MissingPostKey = 'key.post.missing',
  MissingPrivateDataset = 'dataset.private.missing',
  MissingPublicDataset = 'dataset.public.missing',
  MissingTraceParent = 'traceparent.missing',
  MissingUsageDataset = 'dataset.usage.missing',
  PostInvalidProjectId = 'post.project-id.invalid',
  RobotsTxt = 'pathname.robots.txt',
  UnknownError = 'error.unknown',
}
