export enum MetricName {
  InvalidDatabase = 'database.invalid',
  InvalidDatabaseProjectRow = 'database.row.project.invalid',
  InvalidGetKey = 'key.get.invalid',
  InvalidPrivateDataset = 'dataset.private.invalid',
  InvalidPublicDataset = 'dataset.public.invalid',
  InvalidTraceParent = 'traceparent.invalid',
  InvalidUsageDataset = 'dataset.usage.invalid',
  InvalidWorkerMetric = 'quisido.worker.metric.invalid',
  MethodNotAllowed = 'http.4xx.method.not-allowed',
  MissingGetKey = 'key.get.missing',
  MissingPrivateDataset = 'dataset.private.missing',
  MissingPublicDataset = 'dataset.public.missing',
  MissingTraceParent = 'traceparent.missing',
  MissingUsageDataset = 'dataset.usage.missing',
}
