import type { DatadogAggregateRumEvents } from '../datadog-aggregate-rum-events/datadog-aggregate-rum-events.js';

const buildResponseBody = ({
  cumulativeLayoutShiftP50,
  cumulativeLayoutShiftP75,
  domCompleteP50,
  domCompleteP75,
  domContentLoadedP50,
  domContentLoadedP75,
  errorCountP50,
  errorCountP75,
  errorCountP90,
  firstByteP50,
  firstByteP75,
  firstContentfulPaintP50,
  firstContentfulPaintP75,
  firstInputDelayP50,
  firstInputDelayP75,
  interactionToNextPaintP50,
  interactionToNextPaintP75,
  largestContentfulPaintP50,
  largestContentfulPaintP75,
  loadEventP50,
  loadEventP75,
  loadingTimeP50,
  loadingTimeP75,
  sessionTimeSpent,
  viewTimeSpent,
}: DatadogAggregateRumEvents) => ({
  cls: [cumulativeLayoutShiftP50, cumulativeLayoutShiftP75],
  dcl: [domContentLoadedP50, domContentLoadedP75],
  domComplete: [domCompleteP50, domCompleteP75],
  errorCounts: {
    P50: errorCountP50,
    P75: errorCountP75,
    P90: errorCountP90,
  },
  fcp: [firstContentfulPaintP50, firstContentfulPaintP75],
  fip: [firstInputDelayP50, firstInputDelayP75],
  inp: [interactionToNextPaintP50, interactionToNextPaintP75],
  lcp: [largestContentfulPaintP50, largestContentfulPaintP75],
  loadEvent: [loadEventP50, loadEventP75],
  loadingTime: [loadingTimeP50, loadingTimeP75],
  sessionTimeSpent,
  ttfb: [firstByteP50, firstByteP75],
  viewTimeSpent,
});

export default buildResponseBody;
