# yaml-language-server: $schema=../../../schemas/github-action.jsonc
name: GitHub Packages
description: Publishes packages to GitHub Packages

inputs:
  auth-token:
    description: GitHub Packages auth token
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup
    - name: Publish
      run: ./.github/actions/github-packages/github-packages-publish.sh
      shell: bash
      env:
        NPM_AUTH_TOKEN: ${{ inputs.auth-token }}
        NPM_CONFIG_PROVENANCE: true
