import GraphQLObjectQuery from '../utils/graphql-object-query';

export default new GraphQLObjectQuery({
  cost: true,
  viewer: {
    budget: true,
    accounts: {
      __params: {
        filter: {
          accountTag: '$accountTag',
        },
      },

      rumWebVitalsEventsAdaptiveGroups: {
        count: true,

        __params: {
          limit: 1,
          // orderBy: ['avg_cumulativeLayoutShift_ASC'],
          filter: {
            datetime_gt: '$datetime_gt',
          },
        },

        avg: {
          cumulativeLayoutShift: true,
          firstContentfulPaint: true,
          firstInputDelay: true,
          interactionToNextPaint: true,
          largestContentfulPaint: true,
          sampleInterval: true,
          timeToFirstByte: true,
        },

        dimensions: {
          countryName: true,
          cumulativeLayoutShiftElement: true,
          cumulativeLayoutShiftPath: true,
          customTagInternalSxg: true,
          date: true,
          datetimeFifteenMinutes: true,
          datetimeFiveMinutes: true,
          datetimeHalfOfHour: true,
          datetimeHour: true,
          datetimeMinute: true,
          deviceType: true,
          firstInputDelayElement: true,
          firstInputDelayName: true,
          firstInputDelayPath: true,
          largestContentfulPaintElement: true,
          largestContentfulPaintObjectHost: true,
          largestContentfulPaintObjectPath: true,
          largestContentfulPaintObjectScheme: true,
          largestContentfulPaintPath: true,
          refererHost: true,
          refererPath: true,
          refererScheme: true,
          requestHost: true,
          requestPath: true,
          requestScheme: true,
          siteTag: true,
          userAgentBrowser: true,
          userAgentOS: true,
        },

        quantiles: {
          cumulativeLayoutShiftP50: true,
          cumulativeLayoutShiftP75: true,
          cumulativeLayoutShiftP90: true,
          cumulativeLayoutShiftP99: true,
          firstContentfulPaintP50: true,
          firstContentfulPaintP75: true,
          firstContentfulPaintP90: true,
          firstContentfulPaintP99: true,
          firstInputDelayP50: true,
          firstInputDelayP75: true,
          firstInputDelayP90: true,
          firstInputDelayP99: true,
          interactionToNextPaintP50: true,
          interactionToNextPaintP75: true,
          interactionToNextPaintP90: true,
          interactionToNextPaintP99: true,
          largestContentfulPaintP50: true,
          largestContentfulPaintP75: true,
          largestContentfulPaintP90: true,
          largestContentfulPaintP99: true,
          timeToFirstByteP50: true,
          timeToFirstByteP75: true,
          timeToFirstByteP90: true,
          timeToFirstByteP99: true,
        },

        sum: {
          clsGood: true,
          clsNeedsImprovement: true,
          clsPoor: true,
          clsTotal: true,
          fcpGood: true,
          fcpNeedsImprovement: true,
          fcpPoor: true,
          fcpTotal: true,
          fidGood: true,
          fidNeedsImprovement: true,
          fidPoor: true,
          fidTotal: true,
          inpGood: true,
          inpNeedsImprovement: true,
          inpPoor: true,
          inpTotal: true,
          lcpGood: true,
          lcpNeedsImprovement: true,
          lcpPoor: true,
          lcpTotal: true,
          ttfbGood: true,
          ttfbNeedsImprovement: true,
          ttfbPoor: true,
          ttfbTotal: true,
          visits: true,
        },
      },
    },
  },
}).toString();
