export enum MetricName {
  ErrorCode = 'error.code',
  InvalidTraceParent = 'trace-parent.invalid',
  MissingCookieDomain = 'cookie-domain.missing',
  MissingDataBucket = 'bucket.data.missing',
  MissingEnvironmentName = 'environment-name.missing',
  MissingHost = 'host.missing',
  MissingIP = 'ip.missing',
  MissingIsolateEnvironment = 'isolate-environment.missing',
  MissingPrivateDataset = 'dataset.private.missing',
  MissingPublicDataset = 'dataset.public.missing',
  MissingTraceParent = 'trace-parent.missing',
  SetAuthnUserId = 'namespace.authn-user-ids.set',

  // FetchHandler
  InvalidEnvironmentVariable = 'env.invalid',

  // OAuth
  AuthenticationCreated = 'authentication.created',
  AuthenticationRead = 'authentication.read',
  CSRF = 'csrf',
  EmailInsertError = 'query.emails.insert.error',
  EmailInserted = 'query.emails.insert',
  InvalidReturnPath = 'search.state.return-path.invalid',
  InvalidStateSessionId = 'search.state.session-id.invalid',
  MissingReturnPath = 'search.state.return-path.missing',
  MissingStateSearchParam = 'search.state.missing',
  MissingStateSessionId = 'search.state.session-id.missing',
  NonJsonStateSearchParam = 'search.state.invalid.json',
  NonObjectState = 'state.invalid.type',
  OAuthInsertError = 'query.oauth.insert.error',
  OAuthInserted = 'query.oauth.insert',
  OAuthUserIdSelected = 'query.oauth.select.user-id',
  OAuthThrottled = 'oauth.throttled.ip',

  // Patreon
  ForbiddenPatreonIdentityResponse = 'patreon.identity.response.forbidden',
  InvalidInvalidPatreonAccessTokenRequestDescription = 'patreon.access-token.error.invalid-request.description.invalid',
  InvalidPatreonAccessToken = 'patreon.access-token.invalid',
  InvalidPatreonAccessTokenError = 'patreon.access-token.error.invalid',
  InvalidPatreonAccessTokenErrorBody = 'patreon.access-token.error-body.invalid',
  InvalidPatreonAccessTokenRequest = 'patreon.access-token.error.invalid-request',
  InvalidPatreonClientId = 'patreon.client-id.invalid',
  InvalidPatreonGrantCode = 'patreon.grant-code.invalid',
  InvalidPatreonIdentity = 'patreon.identity.invalid',
  InvalidPatreonIdentityAttributes = 'patreon.identity.attributes.invalid',
  InvalidPatreonIdentityData = 'patreon.identity.data.invalid',
  InvalidPatreonIdentityId = 'patreon.identity.id.invalid',
  InvalidPatreonIdentityResponse = 'patreon.identity.response.invalid',
  InvalidPatreonOAuthClientId = 'patreon.oauth-client-id.invalid',
  InvalidPatreonOAuthClientSecret = 'patreon.oauth-client-secret.invalid',
  InvalidPatreonOAuthHost = 'patreon.oauth-host.invalid',
  InvalidPatreonOAuthRedirectUri = 'patreon.oauth-redirect-uri.invalid',
  InvalidPatreonOAuthToken = 'patreon.oauth-token.invalid',
  InvalidPatreonOAuthTokenResponse = 'patreon.oauth-token.response.invalid',
  MissingInvalidPatreonAccessTokenRequestDescription = 'patreon.access-token.error.invalid-request.description.missing',
  MissingPatreonAccessToken = 'patreon.access-token.missing',
  MissingPatreonAccessTokenErrorBody = 'patreon.access-token.error-body.missing',
  MissingPatreonAccessTokenErrorCode = 'patreon.access-token.error.code.missing',
  MissingPatreonIdentityAttributes = 'patreon.identity.attributes.missing',
  MissingPatreonIdentityData = 'patreon.identity.data.missing',
  MissingPatreonIdentityId = 'patreon.identity.id.missing',
  MissingPatreonOAuthClientId = 'patreon.oauth-client-id.missing',
  MissingPatreonOAuthClientSecret = 'patreon.oauth-client-secret.missing',
  MissingPatreonOAuthHost = 'patreon.oauth-host.missing',
  MissingPatreonOAuthRedirectUri = 'patreon.oauth-redirect-uri.missing',
  MissingPatreonRequestCode = 'patreon.request-code.missing',
  PatreonRequest = 'request.patreon',
  UnknownPatreonAccessTokenErrorCode = 'patreon.access-token.error.code.unknown',
  UnknownPatreonIdentityError = 'patreon.identity.error.unknown',

  // Who am I?
  CachedAuthnId = 'authn-id.cached',
  ExpiredAuthnId = 'authn-id.expired',
  InvalidAuthnId = 'cookie.authn-id.invalid',
  MissingAuthnId = 'cookie.authn-id.missing',
  UncachedAuthnId = 'authn-id.uncached',
  WhoAmIThrottled = 'whoami.throttled.ip',

  // quisi.do
  AuthnIdCreated = 'authn-id.created',
  AuthnIdError = 'authn-id.error',
  FaviconIco = 'pathname.favicon.ico',
  InvalidAnalyticsId = 'analytics.id.invalid',
  InvalidAnalyticsMetricName = 'analytics.metric-name.invalid',
  InvalidAnalyticsResponse = 'analytics.response.invalid',
  InvalidAnalyticsSecret = 'analytics.secret.invalid',
  InvalidAuthnUserIdsNamespace = 'namespace.authn-user-ids.invalid',
  InvalidAnalyticsRowBlobIndex = 'analytics.row.blob-index.invalid',
  InvalidAnalyticsRowDoubleIndex = 'analytics.row.double-index.invalid',
  InvalidDatabase = 'database.invalid',
  InvalidOAuthUserId = 'database.oauth.user-id.invalid',
  InvalidUsageDataset = 'dataset.usage.invalid',
  InvalidWorkerMetric = 'worker.metric.invalid',
  MissingAuthnUserIdsNamespace = 'namespace.authn-user-ids.missing',
  MissingDatabase = 'database.missing',
  MissingSessionIdCookie = 'cookie.session-id.missing',
  MissingUsageDataset = 'dataset.usage.missing',
  NotFound = 'pathname.invalid',
  RobotsTxt = 'pathname.robots.txt',
  RootPathname = 'pathname.root',
  UnknownError = 'error.unknown',
}
