export const DAYS_PER_YEAR = 365;
export const HOURS_PER_DAY = 24;
export const MILLISECONDS_PER_SECOND = 1000;
export const MAXIMUM_DAYS_PER_MONTH = 31;
export const MINIMUM_DAYS_PER_MONTH = 28;
export const MINUTES_PER_HOUR = 60;
export const SECONDS_PER_MINUTE = 60;

export const MINUTES_PER_DAY: number = MINUTES_PER_HOUR * HOURS_PER_DAY;

export const SECONDS_PER_DAY: number = SECONDS_PER_MINUTE * MINUTES_PER_DAY;

export const MILLISECONDS_PER_DAY: number =
  MILLISECONDS_PER_SECOND * SECONDS_PER_DAY;
