enum NavigationText {
  AceAlters = 'acealters',
  Applications = 'applications',
  ConnectWithMe = 'connect-with-me',
  Dashboard = 'dashboard',
  Dota2Huds = 'dota2huds',
  GitHub = 'github',
  Home = 'home',
  LinkedIn = 'linkedin',
  Medium = 'medium',
  MoreApplications = 'more-applications',
  MTGPlanechase = 'mtg-planechase',
  Packages = 'packages',
  Portfolio = 'portfolio',
  Publications = 'publications',
  Quisido = 'quisido',
  Quotes = 'quotes',
  RPGOverworldEngine = 'rpg-overworld-engine',
  Settings = 'settings',
  SpriteSheet2Gif = 'spritesheet2gif',
  Tetris3DS = '3ds-tetris',
  Twitter = 'twitter',
}

export default NavigationText;
