/* eslint-disable no-magic-numbers */

export enum ErrorCode {
  // OAuth
  InvalidReturnPath = 11,
  InvalidStateSessionId = 51,
  MissingCookies = 12,
  MissingReturnPath = 9,
  MissingSessionIdCookie = 13,
  MissingStateSearchParam = 4,
  MissingStateSessionId = 10,
  NonJsonStateSearchParam = 5,
  NonObjectState = 8,

  // Patreon
  InvalidPatreonOAuthClientId = 17,
  InvalidPatreonOAuthClientSecret = 19,
  InvalidPatreonOAuthHost = 21,
  InvalidPatreonOAuthRedirectUri = 23,
  MissingPatreonOAuthClientId = 16,
  MissingPatreonOAuthClientSecret = 18,

  // Patreon access token
  ForbiddenPatreonIdentityResponse = 39,
  InvalidInvalidPatreonTokenRequestDescription = 31,
  InvalidPatreonAccessToken = 37,
  InvalidPatreonClientId = 28,
  InvalidPatreonGrantCode = 29,
  InvalidPatreonIdentity = 41,
  InvalidPatreonIdentityData = 43,
  InvalidPatreonIdentityId = 45,
  InvalidPatreonIdentityResponse = 38,
  InvalidPatreonOAuthToken = 35,
  InvalidPatreonTokenErrorResponse = 26,
  InvalidPatreonTokenErrorResponseBody = 24,
  InvalidPatreonTokenRequest = 32,
  InvalidPatreonTokenResponse = 34,
  MissingInvalidPatreonTokenRequestDescription = 30,
  MissingPatreonAccessToken = 36,
  MissingPatreonIdentityData = 42,
  MissingPatreonIdentityId = 44,
  MissingPatreonOAuthHost = 52,
  MissingPatreonRequestCode = 15,
  MissingPatreonTokenErrorResponseBody = 25,
  MissingPatreonTokenErrorResponseCode = 27,
  UnknownPatreonIdentityError = 40,
  UnknownPatreonTokenErrorResponseCode = 33,

  // quisi.do
  CSRF = 14,
  InvalidAnalyticsId = 53,
  InvalidAnalyticsSecret = 54,
  InvalidAuthnUserIdsNamespace = 20,
  InvalidCause = 3,
  InvalidDatabase = 47,
  InvalidIsolateEnvironment = 6,
  InvalidOAuthUserId = 48,
  InvalidUsageDataset = 50,
  InvalidUnknownEnv = 22,
  MissingAnalyticsId = 55,
  MissingAnalyticsSecret = 56,
  MissingAuthnUserIdsNamespace = 49,
  MissingDatabase = 46,
  MissingIsolateEnvironment = 7,
  NotFound = 404,
  TooManyRequests = 429,
  Unknown = 1,
  UnknownCause = 2,
}
