# yaml-language-server: $schema=../../schemas/github-workflow.jsonc
name: Continuous integration failure

concurrency:
  cancel-in-progress: true
  group: continunous-integration-failure-${{ github.event.workflow_run.pull_requests[0].number }}

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Continuous integration

jobs:
  copilot:
    name: Copilot
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      issues: write
      pull-requests: write
    steps:
      - name: Comment
        uses: actions/github-script@v9
        with:
          script: |
            /**
             * Deliberately ignore forked pull requests. They will not be in
             * this array.
             */
            const [pullRequest] =
              context.payload.workflow_run.pull_requests ?? [];
            if (pullRequest === undefined) {
              return;
            }

            const { owner, repo } = context.repo;
            const { html_url: runUrl, id: runId, name: runName } =
              context.payload.workflow_run;

            const { data: { jobs } } =
              await github.rest.actions.listJobsForWorkflowRun({
                owner,
                per_page: 100,
                repo,
                run_id: runId,
              });

            /**
             * If the run failure was not due to a specific job (e.g.
             * infrastructure), do not notify Copilot.
             */
            const isFailed = ({ conclusion }) => conclusion === 'failure';
            const failedJobs = jobs.filter(isFailed);
            if (failedJobs.length === 0) {
              return;
            }

            const toListMarkdown = ({ html_url: url, name }) =>
              `- [${name}](${url})`;

            const { serverUrl } = context;
            const { number: prNumber } = pullRequest;
            const prUrl = `${serverUrl}/${owner}/${repo}/pull/${prNumber}`;
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner,
              repo,
              body: [
                `Continuous integration run ["${runName}"](${runUrl}) failed ` +
                `for [pull request #${prNumber}](${prUrl}).`,

                'Please analyze the failures and submit a pull request that ' +
                'contains the smallest possible fix.',

                '**Failed jobs:**\n' +
                `${failedJobs.map(toListMarkdown).join('\n')}`,

                '**Acceptance criteria:** `npm test` must pass.',
              ].join('\n\n'),
            });
