name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          check-latest: true
          node-version-file: .nvmrc

      - name: Install dependencies
        run: |
          npm install
          npm run build --workspace=packages/quisido
          npm install
