# yaml-language-server: $schema=../../schemas/github-workflow.jsonc
name: Pull request

concurrency:
  cancel-in-progress: true
  group: pull-request-${{ github.event.pull_request.number }}

on:
  pull_request:

permissions:
  contents: read

jobs:
  # Stage 1: actionlint, auto-merge, build, dependency-review
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Install
        env:
          ACTIONLINT_VERSION: 1.7.12
        run: >-
          curl --fail --location --show-error --silent
          "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz" |
          tar --directory "$RUNNER_TEMP" --extract --gzip actionlint;
      - name: Lint
        run: "$RUNNER_TEMP/actionlint";

  auto-merge:
    name: Auto-merge
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write      # gh pr merge
      pull-requests: write # gh pr merge
    steps:
      - name: Get authors
        id: commits
        run: |-
          DEPENDABOT=$( \
            gh api \
              "repos/$GITHUB_REPOSITORY/compare/$DEFAULT_BRANCH...$HEAD_SHA" \
              --jq '[.commits[] | (.author.login // "")] | all(.[]; . == "dependabot[bot]")' \
              2>/dev/null || \
            echo 'false' \
          );
          echo "dependabot=$DEPENDABOT" >> "$GITHUB_OUTPUT";
        env:
          DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
      - name: ${{ steps.commits.outputs.dependabot == 'true' && 'Enable' || 'Disable' }}
        run: gh pr merge ${{ env.FLAGS }} "$HTML_URL"
        env:
          FLAGS: ${{ steps.commits.outputs.dependabot == 'true' && '--auto --squash' || '--disable-auto' }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HTML_URL: ${{github.event.pull_request.html_url}}

  build:
    name: Build
    if: github.event.pull_request.head.repo.full_name == github.repository
    environment: continuous-integration
    runs-on: ubuntu-latest
    services:
      datadog-agent: &datadog-agent
        image: datadog/agent:latest
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_ENV: ci
          DD_HOSTNAME: none
          DD_INSIDE_CI: true
        ports:
          - 8126:8126
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Build
        uses: ./.github/actions/build
        with:
          environment: staging

  dependency-review:
    name: Dependency review
    if: github.event.pull_request.head.repo.full_name == github.repository
    environment: continuous-integration
    runs-on: ubuntu-latest
    permissions:
      contents: read       # git checkout
      pull-requests: write # status checks
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Review
        uses: actions/dependency-review-action@v5

  # Stage 2: lighthouse, test, webhint
  lighthouse:
    name: Lighthouse
    if: github.event.pull_request.head.repo.full_name == github.repository
    environment: continuous-integration
    needs: build
    runs-on: ubuntu-latest
    services:
      datadog-agent: *datadog-agent
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Lighthouse
        uses: ./.github/actions/lighthouse-ci

  test:
    name: Test
    if: github.event.pull_request.head.repo.full_name == github.repository
    environment: continuous-integration
    needs: build
    runs-on: ubuntu-latest
    services:
      datadog-agent: *datadog-agent
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Test
        uses: ./.github/actions/test

  webhint:
    name: Webhint
    if: github.event.pull_request.head.repo.full_name == github.repository
    environment: continuous-integration
    needs: build
    runs-on: ubuntu-latest
    services:
      datadog-agent: *datadog-agent
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Audit
        uses: ./.github/actions/webhint-ci

  # Stage 3: codecov
  codecov:
    name: Codecov
    if: github.event.pull_request.head.repo.full_name == github.repository
    environment: continuous-integration
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read # git checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Upload
        uses: ./.github/actions/codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
